In [4]:
#Librerias
import pandas as pd
import os
import glob

In [5]:
#Traemos el df_final_alternativo
df_final_alternativo = pd.read_csv('df_final_alternativo.csv')
print('Shape del df_final_alternativo: ',df_final_alternativo.shape)

#Traemos los features comerciales
Esquinas = pd.read_csv('Data/Damero_feature_comercios.csv') #Estas son todas las esquinas de la ciudad, lo usamos para la prediccion final
df4 = pd.read_csv('Data/PV_R_feature_comercios.csv')
print('Shape del df3 (Lo usamos mas adelante para las predicciones finales): ',Esquinas.shape)
print('Shape del df4: ',df4.shape)

Shape del df_final_alternativo:  (784, 35)
Shape del df3 (Lo usamos mas adelante para las predicciones finales):  (15406, 3)
Shape del df4:  (1048575, 6)

C:\Users\DataScience\AppData\Local\Temp\ipykernel_13368\272727109.py:7: DtypeWarning: Columns (1,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df4 = pd.read_csv('Data/PV_R_feature_comercios.csv')

In [6]:
#Eliminamos todos los nulls de ambos data frames
Esquinas = Esquinas.dropna()
print(Esquinas.isnull().sum())
print('')
df4 = df4.dropna()
print(df4.isnull().sum())

fid           0
NOMBRE        0
heatmap_co    0
dtype: int64

PuntoNumer    0
PuntoTipo     0
Y_WGS         0
X_WGS         0
heatmap_co    0
ID            0
dtype: int64

In [7]:
df_final_alternativo

,ID,Numero,CantidadNum,fid,totalpobl,hogares,Desocupado,0 - 14,65 y más,Inicial (j,...,Seccion,ClasificacionNum2,Tipo de punto_Rulero,TipoResiduo_Papel,TipoResiduo_Plástico,"TipoResiduo_Vidrio, Metal, Tetra",macroz_2_Comercial,macroz_2_Especial Parque Gral. San Marti?n,macroz_2_Residencial suburbano,macroz_2_Residencial urbano
0,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,8.0,0,0,0,1,0,0,0,0,1
1,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,8.0,0,0,0,1,0,0,0,0,1
2,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,8.0,0,0,0,1,0,0,0,0,1
3,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,8.0,0,0,0,1,0,0,0,0,1
4,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,8.0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,2.0,0,1,0,0,0,0,0,0,1
780,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,2.0,0,1,0,0,0,0,0,0,1
781,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,2.0,0,1,0,0,0,0,0,0,1
782,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,2.0,0,1,0,0,0,0,0,0,1
783,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,2.0,0,1,0,0,0,0,0,0,1

In [8]:
#Veamos sus tamaños originales
print('El tamaño del df4 es :', df4.shape)

El tamaño del df4 es : (85, 6)

In [9]:
df4

,PuntoNumer,PuntoTipo,Y_WGS,X_WGS,heatmap_co,ID
0,1.0,Punto Verde,-32.868810,-68.876161,0.38260,PV1
1,1.0,Rulero,-32.862295,-68.834208,4.22958,R1
2,2.0,Punto Verde,-32.866235,-68.868028,5.83923,PV2
3,2.0,Rulero,-32.865605,-68.861388,0.24251,R2
4,3.0,Punto Verde,-32.866075,-68.853758,4.79120,PV3
...,...,...,...,...,...,...
81,50.0,Punto Verde,-32.870967,-68.831296,12.55573,PV50
82,52.0,Punto Verde,-32.877466,-68.855005,33.46423,PV52
83,53.0,Punto Verde,-32.869812,-68.859035,4.97157,PV53
84,54.0,Plaza de los Constituyentes,-32.864723,-68.849545,6.68478,54
85,56.0,Plaza de los Constituyentes,-32.865930,-68.841926,10.58380,56

In [10]:
#Ahora toca hacer el merge con el nuevo data set de densidad comercial
df_final_alternativo_2 = pd.merge(df_final_alternativo, df4 ,how= 'left', on=['ID'])
df_final_alternativo_2

,ID,Numero,CantidadNum,fid,totalpobl,hogares,Desocupado,0 - 14,65 y más,Inicial (j,...,"TipoResiduo_Vidrio, Metal, Tetra",macroz_2_Comercial,macroz_2_Especial Parque Gral. San Marti?n,macroz_2_Residencial suburbano,macroz_2_Residencial urbano,PuntoNumer,PuntoTipo,Y_WGS,X_WGS,heatmap_co
0,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,0,0,0,0,1,1.0,Punto Verde,-32.868810,-68.876161,0.38260
1,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,0,0,0,0,1,1.0,Punto Verde,-32.868810,-68.876161,0.38260
2,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,0,0,0,0,1,1.0,Punto Verde,-32.868810,-68.876161,0.38260
3,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,0,0,0,0,1,1.0,Punto Verde,-32.868810,-68.876161,0.38260
4,PV1,1,2.0,1.0,848.0,259.0,39.0,190.0,97.0,35.0,...,0,0,0,0,1,1.0,Punto Verde,-32.868810,-68.876161,0.38260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,0,0,0,0,1,40.0,Rulero,-32.901425,-68.848368,9.73597
816,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,0,0,0,0,1,40.0,Rulero,-32.901425,-68.848368,9.73597
817,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,0,0,0,0,1,40.0,Rulero,-32.901425,-68.848368,9.73597
818,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,0,0,0,0,1,40.0,Rulero,-32.901425,-68.848368,9.73597
819,R40,40,1.0,72.0,528.0,188.0,11.0,87.0,102.0,16.0,...,0,0,0,0,1,40.0,Rulero,-32.901425,-68.848368,9.73597

In [11]:
df_final_alternativo_2 = df_final_alternativo_2.drop(['PuntoTipo','Y_WGS','X_WGS', 'PuntoNumer'], axis=1)

In [12]:
df_final_alternativo_2['ClasificacionNum2'].value_counts() / df_final_alternativo_2.shape[0]

0    0.7
1    0.3
Name: ClasificacionNum2, dtype: float64

In [13]:
#Hay algunos nulos asi que los eliminamos
df_final_alternativo_2.isnull().sum()

ID                                            0
Numero                                        0
CantidadNum                                   0
fid                                           0
totalpobl                                     0
hogares                                       0
Desocupado                                    0
0 - 14                                        0
65 y más                                      0
Inicial (j                                    0
Primario                                      0
EGB                                           0
Secundario                                    0
Polimodal                                     0
Superior n                                    0
Universita                                    0
Post unive                                    0
lee_y _esc                                    0
NoLee_ni_e                                    0
Hacinamien                                    0
sin red ag                                    0
Sin cloaca                                    0
toponimo_i                                    0
dens pob                                      0
Area_Has                                      0
Seccion                                       0
ClasificacionNum2                             0
Tipo de punto_Rulero                          0
TipoResiduo_Papel                             0
TipoResiduo_Plástico                          0
TipoResiduo_Vidrio, Metal, Tetra              0
macroz_2_Comercial                            0
macroz_2_Especial Parque Gral. San Marti?n    0
macroz_2_Residencial suburbano                0
macroz_2_Residencial urbano                   0
heatmap_co                                    2
dtype: int64

In [14]:
df_final_alternativo_2 = df_final_alternativo_2.dropna()

In [15]:
#Chequeamos ahora los nulos
df_final_alternativo_2.dtypes

ID                                             object
Numero                                          int64
CantidadNum                                   float64
fid                                           float64
totalpobl                                     float64
hogares                                       float64
Desocupado                                    float64
0 - 14                                        float64
65 y más                                      float64
Inicial (j                                    float64
Primario                                      float64
EGB                                           float64
Secundario                                    float64
Polimodal                                     float64
Superior n                                    float64
Universita                                    float64
Post unive                                    float64
lee_y _esc                                    float64
NoLee_ni_e                                    float64
Hacinamien                                    float64
sin red ag                                    float64
Sin cloaca                                    float64
toponimo_i                                    float64
dens pob                                      float64
Area_Has                                      float64
Seccion                                       float64
ClasificacionNum2                               int64
Tipo de punto_Rulero                            int64
TipoResiduo_Papel                               int64
TipoResiduo_Plástico                            int64
TipoResiduo_Vidrio, Metal, Tetra                int64
macroz_2_Comercial                              int64
macroz_2_Especial Parque Gral. San Marti?n      int64
macroz_2_Residencial suburbano                  int64
macroz_2_Residencial urbano                     int64
heatmap_co                                    float64
dtype: object

In [17]:
Esquinas

         fid                    NOMBRE  heatmap_co
0          1  MOSCONI ENRIQUE GRAL ING     7.96807
1          2  MOSCONI ENRIQUE GRAL ING     7.96908
2          3  MOSCONI ENRIQUE GRAL ING     7.96807
3          4  MOSCONI ENRIQUE GRAL ING     6.73568
4          5  MOSCONI ENRIQUE GRAL ING     7.96807
...      ...                       ...         ...
15401  15402        Dr. SALOMON MIYARA     1.93049
15402  15403        Dr. SALOMON MIYARA     0.36526
15403  15404        Dr. SALOMON MIYARA     3.01880
15404  15405        Dr. SALOMON MIYARA     0.83134
15405  15406        Dr. SALOMON MIYARA     0.36526

[14117 rows x 3 columns]

In [16]:
#Terminamos la limpieza asi que guardamos el df_final_alternativo_2
df_final_alternativo_2.to_csv("df_final_alternativo_2.csv", index=False, encoding='utf-8-sig')

In [18]:
#Guardamos el data set de las esquinas
Esquinas.to_csv("Esquinas.csv", index=False, encoding='utf-8-sig')